variables:
    PEEK_NODE_VERSION: v7.1.0
    LATEST_NODE_VERSION: v12.16.1
    NVM_DIR: /usr/local/nvm

stages:
    - test


unit_tests_linux:
    allow_failure: false
    image: nexus.synerty.com:5000/vortexpy-linux
    only:
        - web
        - triggers
        - merge_requests
    script:
        - export PIP_INDEX=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/pypi
        - export PIP_INDEX_URL=http://${NEXUS_USER}:${NEXUS_PASSWORD}@${NEXUS_URL}/repository/pypi-all/simple
        - export PIP_TRUSTED_HOST=${NEXUS_URL}
        - pip install subunitreporter junitxml
        - python setup.py develop
        - trial --reporter=subunit `find vortex/ -name "*Test.py"` | subunit-1to2 | subunit2junitxml -o report.xml
    stage: test
    artifacts:
        reports:
            junit: report.xml
    tags:
        - linux



sonar:
    allow_failure: false
    image: nexus.synerty.com:5000/vortexpy-linux
    only:
        - web
        - triggers
        - merge_requests
    stage: test
    script:
        - echo "Run sonar-scanner"
        - source $NVM_DIR/nvm.sh
        - nvm use $LATEST_NODE_VERSION
        - export NODE_PATH=`npm root -g`
        - npm install -g typescript@3.7.5
        - sonar-scanner
    tags:
        - linux

